// One listing per toolset: the MCPB bundle, Smithery server and MCP Registry entry share these names.
export const LISTINGS = {
    all: {
        title: 'AutomationNation Data Tools',
        smithery: 'data-tools',
        icon: 'automationnation.png',
        description: '17 data tools for AI agents: Google Flights, Hotels, Shopping, News, Images, Videos, Jobs and Trends, Google Maps leads, Ads Transparency, YouTube transcripts, app reviews and AI visibility.',
        keywords: ['google', 'scraper', 'travel', 'shopping', 'news', 'jobs', 'trends', 'youtube', 'leads', 'app-reviews', 'ai-visibility'],
    },
    travel: {
        title: 'Google Flights & Hotels',
        smithery: 'google-flights',
        icon: 'google-flights-scraper.png',
        description: 'Live Google Flights fares and Google Hotels prices for AI agents: any route and date, or any city, area or landmark.',
        keywords: ['google-flights', 'google-hotels', 'flights', 'hotels', 'travel', 'airfare'],
    },
    youtube: {
        title: 'YouTube Transcripts',
        smithery: 'youtube-transcripts',
        icon: 'youtube-transcript-scraper.png',
        description: 'Transcripts of any YouTube video, Short, channel or playlist, with optional timestamps and translation, for summaries, quotes and RAG.',
        keywords: ['youtube', 'transcript', 'captions', 'subtitles', 'video'],
    },
    shopping: {
        title: 'Google Shopping',
        smithery: 'google-shopping',
        icon: 'google-shopping-scraper.png',
        description: 'Google Shopping results for any product and country: prices, discounts, stores, delivery, ratings and reviews.',
        keywords: ['google-shopping', 'prices', 'ecommerce', 'price-comparison', 'products'],
    },
    news: {
        title: 'Google News',
        smithery: 'google-news',
        icon: 'google-news-scraper.png',
        description: 'Google News for any topic, company or person: headlines, publishers, publish times and article URLs, newest first if you like.',
        keywords: ['google-news', 'news', 'headlines', 'media-monitoring'],
    },
    'google-search': {
        title: 'Google Search Verticals',
        smithery: 'google-search',
        icon: 'google-images-scraper.png',
        description: 'Google Shopping, News, Images and Videos results as data for AI agents, in any country and language.',
        keywords: ['google', 'serp', 'google-images', 'google-videos', 'google-news', 'google-shopping'],
    },
    jobs: {
        title: 'Google Jobs',
        smithery: 'google-jobs',
        icon: 'google-jobs-scraper.png',
        description: 'Job listings from Google Jobs in 26 countries: title, company, salary, location, remote flag, description and apply links.',
        keywords: ['google-jobs', 'jobs', 'job-search', 'salaries', 'recruiting'],
    },
    trends: {
        title: 'Google Trends',
        smithery: 'google-trends',
        icon: 'google-trends-scraper.png',
        description: 'Google Trends interest over time, top regions and rising searches for any keywords, plus what is trending right now.',
        keywords: ['google-trends', 'trends', 'keyword-research', 'trending'],
    },
    leads: {
        title: 'Google Maps Leads',
        smithery: 'google-maps-leads',
        icon: 'google-maps-leads.png',
        description: 'Local business leads from Google Maps in any country, with emails, phones, websites and lead scores; UK leads add Companies House directors.',
        keywords: ['google-maps', 'leads', 'lead-generation', 'b2b', 'local-business', 'emails'],
    },
    ads: {
        title: 'Google Ads Transparency',
        smithery: 'google-ads-transparency',
        icon: 'google-ads-transparency-scraper.png',
        description: "Every ad a brand runs on Google Search, YouTube and Display, with texts, landing pages and run dates, from Google's Ads Transparency Center.",
        keywords: ['google-ads', 'ads-transparency', 'competitor-ads', 'ppc', 'ad-library'],
    },
    'app-reviews': {
        title: 'App Store & Google Play Reviews',
        smithery: 'app-reviews',
        icon: 'app-store-review-miner.png',
        description: 'App Store and Google Play reviews for any app and country, plus AI analysis of bugs, feature requests and sentiment.',
        keywords: ['app-store', 'google-play', 'app-reviews', 'reviews', 'sentiment'],
    },
    'ai-visibility': {
        title: 'AI Visibility & AI Overviews',
        smithery: 'ai-visibility',
        icon: 'ai-visibility-tracker.png',
        description: 'Check whether Google AI Overviews, Gemini and Claude mention and cite your brand, and which competitors they cite instead.',
        keywords: ['ai-visibility', 'aeo', 'geo', 'ai-overviews', 'brand-monitoring', 'seo'],
    },
};
