// Copies the price line of each Actor from marketing/actors.json into src/prices.js,
// so tool descriptions quote the same prices as the Store pages. Run after a price change.
import { readFileSync, writeFileSync } from 'node:fs';

const actors = JSON.parse(readFileSync(new URL('../../marketing/actors.json', import.meta.url), 'utf8'));
const prices = Object.fromEntries((Array.isArray(actors) ? actors : actors.actors).map((a) => [a.slug, a.price]));
writeFileSync(new URL('../src/prices.js', import.meta.url), `// Generated by scripts/sync-prices.mjs from marketing/actors.json. Don't edit by hand.\nexport default ${JSON.stringify(prices, null, 4)};\n`);
console.log(`src/prices.js: ${Object.keys(prices).length} prices`);
