// Generated by scripts/sync-prices.mjs from marketing/actors.json. Don't edit by hand.
export default {
    "ai-visibility-tracker": "$0.05 per answer checked ($0.04 on Gold) + $0.50 per optional report",
    "google-jobs-scraper": "$2 per 1,000 jobs ($1.50 on paid plans) + $0.03 per search",
    "youtube-transcript-scraper": "$1.50 per 1,000 transcripts ($1.20 on Gold and above)",
    "google-shopping-scraper": "$1 per 1,000 products ($0.80 on Gold and above)",
    "google-flights-scraper": "$0.20 per 1,000 flights ($0.16 on Gold and above)",
    "google-hotels-scraper": "$1 per 1,000 hotels ($0.80 on Gold and above)",
    "google-ads-transparency-scraper": "$1 per 1,000 ads ($0.80 on Gold and above)",
    "google-news-scraper": "$1 per 1,000 articles ($0.80 on Gold and above)",
    "google-images-scraper": "$0.25 per 1,000 images ($0.20 on Gold and above)",
    "google-custom-search-api": "$5 per 1,000 searches of up to 10 results ($4 on Gold and above)",
    "google-videos-scraper": "$1 per 1,000 videos ($0.80 on Gold and above)",
    "google-trends-scraper": "$1 per 1,000 keyword reports ($0.27–$0.90 on paid plans) · $0.50 per 1,000 trending searches",
    "app-store-reviews-scraper": "$0.08 per 1,000 reviews ($0.05–$0.07 on paid plans)",
    "google-play-reviews-scraper": "$0.08 per 1,000 reviews ($0.05–$0.07 on paid plans)",
    "aeo-auditor": "$0.04 per keyword ($0.032 on Gold), plus $2 per run from 17 Nov 2026; $0.01 per keyword until 16 Oct 2026",
    "google-maps-leads": "$0.03 per lead ($0.024 on Gold)",
    "uk-business-leads": "$0.05 per lead ($0.04 on Gold)",
    "app-store-review-miner": "$0.05 per app report ($0.04 on Gold)",
    "companies-house-leads": "$0.008 per lead",
    "contact-waterfall-enrichment": "$0.015 per company"
};
